version: '3.8'

services:
  ollama:
    image: debian:12
    container_name: ollama
    tty: true
    stdin_open: true
    command: bash -c "
      apt update && apt install -y curl python3 python3-pip && \
      curl -fsSL https://ollama.com/install.sh | sh && \
      ollama serve"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html:ro
